services:
  app:
    build: .
    container_name: myflixi-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Protect node_modules from being overwritten
    environment:
      - NODE_ENV=development
      - FEBBOX_UI_COOKIE=${FEBBOX_UI_COOKIE}
      - ADMIN_SECRET=${ADMIN_SECRET}
    restart: unless-stopped
