name = "movie-edge-resolver"
main = "src/worker.ts"
compatibility_date = "2024-05-03"
compatibility_flags = ["nodejs_compat"]

[vars]
# You'll need to add your origin API URL here if you want the worker to fallback
ORIGIN_API = "https://your-api.com"

[[kv_namespaces]]
binding = "MYFLIXI_CACHE"
id = "xxxx" 
preview_id = "xxxx"

[[durable_objects.bindings]]
name = "FEBBOX_SESSION"
class_name = "FebBoxSession"

[[migrations]]
tag = "v1"
new_classes = ["FebBoxSession"]

[observability]
enabled = true
